"use client";
import { onAuthStateChanged, signInWithEmailAndPassword, signInWithPopup, signOut, createUserWithEmailAndPassword, type User } from "firebase/auth";
import * as React from "react";
import { auth, googleProvider, isFirebaseConfigured } from "@/lib/firebase/client";
import type { UserProfile } from "@/lib/types";
type AuthContextValue = { user: User | null; profile: UserProfile | null; loading: boolean; signInWithGoogle: () => Promise<void>; signInWithEmail: (email: string, password: string) => Promise<void>; registerWithEmail: (email: string, password: string) => Promise<void>; signInWithDiscord: () => Promise<void>; logout: () => Promise<void>; };
const AuthContext = React.createContext<AuthContextValue | undefined>(undefined);
export function AuthProvider({ children }: { children: React.ReactNode }) { const [user, setUser] = React.useState<User | null>(null); const [loading, setLoading] = React.useState(true); React.useEffect(() => { if (!isFirebaseConfigured || !auth) { setLoading(false); return; } return onAuthStateChanged(auth, (nextUser) => { setUser(nextUser); setLoading(false); }); }, []); const profile: UserProfile | null = user ? { uid: user.uid, displayName: user.displayName ?? "Captain", email: user.email ?? "", photoURL: user.photoURL ?? undefined, roles: ["user"], favoriteDeckIds: [], bookmarkedLeaderIds: [], followedPlayerIds: [] } : null; const value: AuthContextValue = { user, profile, loading, async signInWithGoogle() { if (!auth) throw new Error("Firebase is not configured. Add NEXT_PUBLIC_FIREBASE_* environment variables."); await signInWithPopup(auth, googleProvider); }, async signInWithEmail(email, password) { if (!auth) throw new Error("Firebase is not configured. Add NEXT_PUBLIC_FIREBASE_* environment variables."); await signInWithEmailAndPassword(auth, email, password); }, async registerWithEmail(email, password) { if (!auth) throw new Error("Firebase is not configured. Add NEXT_PUBLIC_FIREBASE_* environment variables."); await createUserWithEmailAndPassword(auth, email, password); }, async signInWithDiscord() { throw new Error("Discord OAuth provider placeholder is ready for Firebase provider configuration."); }, async logout() { if (auth) await signOut(auth); setUser(null); } }; return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>; }
export function useAuth() { const context = React.useContext(AuthContext); if (!context) throw new Error("useAuth must be used within AuthProvider"); return context; }
