import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { tournaments } from "@/lib/mock-data";
import { createMetadata } from "@/lib/seo";
import { getTournamentById } from "@/lib/services/firestore";
export async function generateStaticParams() { return tournaments.map((event) => ({ id: event.id })); }
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const event = await getTournamentById(id); return createMetadata({ title: event?.name ?? "Tournament", description: event?.bracketSummary, path: `/tournaments/${id}` }); }
export default async function TournamentPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const event = await getTournamentById(id); if (!event) notFound(); return <div className="space-y-6"><div><Badge variant="outline">{event.region} - {event.opSet}</Badge><h1 className="mt-4 text-4xl font-black sm:text-6xl">{event.name}</h1><p className="mt-4 max-w-3xl text-muted-foreground">{event.bracketSummary}</p></div><div className="grid gap-5 md:grid-cols-4"><Stat label="Players" value={String(event.players)} /><Stat label="Matches" value={String(event.stats.totalMatches)} /><Stat label="Conversion" value={`${event.stats.conversionRate}%`} /><Stat label="Rogue share" value={`${event.stats.rogueShare}%`} /></div><Card><CardHeader><CardTitle>Deck distribution</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Leader</TableHead><TableHead>Count</TableHead><TableHead>Share</TableHead></TableRow></TableHeader><TableBody>{event.deckDistribution.map((row) => <TableRow key={row.leaderId}><TableCell>{row.leaderName}</TableCell><TableCell>{row.count}</TableCell><TableCell>{((row.count / event.players) * 100).toFixed(1)}%</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <Card><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></CardContent></Card>; }
